# Generated by Django 5.1 on 2024-09-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTourNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('buttonname', models.CharField(max_length=100, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='booktournow')),
            ],
            options={
                'verbose_name': 'Book A Tour Now',
                'verbose_name_plural': 'Book A Tour Now',
                'ordering': ('description1',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField(max_length=20)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='CreateYourTourStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField()),
                ('style_photo', models.ImageField(blank=True, null=True, upload_to='createyourtourstyle/%Y/%m/%d/')),
                ('buttonname', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=True)),
            ],
            options={
                'verbose_name': 'Tour Style',
                'verbose_name_plural': 'Tour Styles',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='DiscoverNewHorizon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='discoverNewHorizon/%Y/%m/%d/')),
                ('buttonname', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Discover New Horizon',
                'verbose_name_plural': 'Discover New Horizons',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='headerfooter')),
            ],
            options={
                'verbose_name': 'headerfooter',
                'verbose_name_plural': 'headerandfooter',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fl-bigmug-line-equalization3', max_length=100)),
            ],
            options={
                'verbose_name': 'Our Service',
                'verbose_name_plural': 'Our Services',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OurStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('phone_number', models.TextField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ourstaff/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Our Staff',
                'verbose_name_plural': 'Our Staff',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_swiper', models.ImageField(blank=True, null=True, upload_to='swiper')),
                ('advertise1', models.CharField(max_length=100, unique=True)),
                ('text12', models.CharField(max_length=100, unique=True)),
                ('text21', models.CharField(max_length=100, unique=True)),
                ('button', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Swiper',
                'verbose_name_plural': 'Swipers',
                'ordering': ('text12',),
            },
        ),
        migrations.CreateModel(
            name='HotTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hottours/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reviewstar', models.PositiveSmallIntegerField()),
                ('reviews', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('tourstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='home.createyourtourstyle')),
            ],
            options={
                'verbose_name': 'Hot Tour',
                'verbose_name_plural': 'Hot Tours',
                'ordering': ('date',),
            },
        ),
    ]
